

# generic_hw_control_loop:
#   loop_hz: 1000 # 250 to emulate serial pause COMMAND_PERIOD 0.0055 , SERIAL_PAUSE 0.004
#   cycle_time_error_threshold: 0.1 # normal é 0.1

# Settings for ros_control hardware interface (used in generic_hw_interface.cpp)
hardware_interface:
    joints:
      - joint_base_mancal
      - joint_mancal_elo1
      - joint_elo1_elo2
      - joint_elo2_gripper
      - joint_gripper_left_finger
      - joint_gripper_right_finger
    sim_control_mode: 0 # 0: position, 1: velocity

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 200

arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_base_mancal
    - joint_mancal_elo1
    - joint_elo1_elo2
    - joint_elo2_gripper
  gains:
    joint_base_mancal:
      p: 30.0
      d: 10.0
      i: 0.0
      i_clamp: 1.0
    joint_mancal_elo1:
      p: 30.0
      d: 10.0
      i: 0.0
      i_clamp: 1.0
    joint_elo1_elo2:
      p: 30.0
      d: 10.0
      i: 0.0
      i_clamp: 1.0
    joint_elo2_gripper:
      p: 30.0
      d: 10.0
      i: 0.0
      i_clamp: 1.0

hand_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_gripper_left_finger
    - joint_gripper_right_finger
  gains:
    joint_gripper_left_finger:
      p: 30.0
      d: 0.0
      i: 0.0
      i_clamp: 1.0
    joint_gripper_right_finger:
      p: 30.0
      d: 0.0
      i: 0.0
      i_clamp: 1.0

# controller_list:
#   - name: arm_position_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: True
#     joints:
#       - joint_base_mancal
#       - joint_mancal_elo1
#       - joint_elo1_elo2
#       - joint_elo2_gripper
      
#   - name: hand_position_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: True
#     joints:
#       - joint_gripper_left_finger   
#       - joint_gripper_right_finger   