manipulator_planning:
  chain_start: "base_link"
  chain_end: "ee_center"
  timeout: 0.005
  num_samples: 1000
  joints:
    - joint_base_mancal
    - joint_mancal_link1
    - joint_link1_link2
    - joint_link2_link3
    - joint_link3_gripper
  
